# Generated by Django 5.2.8 on 2026-07-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_blogs_blog_body_alter_blogs_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
